name: Microsoft.Fast-Blazor Publish

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  project: 'src\Microsoft.Fast.Components.FluentUI\Microsoft.Fast.Components.FluentUI.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(project)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    nugetConfigPath: $(project)

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/Microsoft.Fast.Components.FluentUI.csproj'
    versioningScheme: 'off'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'FAST-NuGet-Publishing-SC'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: |
      **/*.dll
      **/*.nupkg
    UseMinimatch: true
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : { },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : { },
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '200'
    MaxRetryAttempts: '5'
  displayName: Sign Agent Assemblies (Authenticode Signing)

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)\*.nupkg;'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetServiceConnect'