# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
  displayName: 'Create Package'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'FAST-NuGet-Publishing-SC'
    FolderPath: '$(agent.builddirectory)\src\Microsoft.Fast.Components.FluentUI\bin'
    Pattern: |
      Microsoft.Fast.Components.FluentUI.dll
    UseMinimatch: true
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetSign",
            "Parameters" : [ ],
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        },
        {
            "KeyCode" : "CP-401405",
            "OperationCode" : "NuGetVerify",
            "Parameters" : [ ],
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
  displayName: Sign Agent Assemblies (Authenticode Signing)

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: 'src/Microsoft.Fast.Components.FluentUI/bin/Release/*.nupkg;!src/Microsoft.Fast.Components.FluentUI/bin/Release/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NugetServiceConnect'